/**
 * 限时购商品关联管理API接口模块
 * 提供限时购活动与商品关联关系的增删改查功能
 * generated by zhangsan 2025
 */
import request from '@/utils/request'

/**
 * 获取限时购商品关联列表
 * @param {Object} params - 查询参数对象
 * @param {number} params.pageNum - 页码
 * @param {number} params.pageSize - 每页大小
 * @param {number} params.flashPromotionId - 限时购活动ID
 * @returns {Promise} 返回包含限时购商品关联列表的Promise对象
 * generated by zhangsan 2025
 */
export function fetchList(params) {
  return request({
    url:'/flashProductRelation/list',
    method:'get',
    params:params
  })
}

/**
 * 创建限时购商品关联
 * @param {Object} data - 限时购商品关联数据对象
 * @param {number} data.flashPromotionId - 限时购活动ID
 * @param {number} data.flashPromotionSessionId - 限时购场次ID
 * @param {number} data.productId - 商品ID
 * @param {number} data.flashPrice - 限时购价格
 * @param {number} data.flashCount - 限时购数量
 * @param {number} data.sort - 排序
 * @returns {Promise} 返回创建结果的Promise对象
 * generated by zhangsan 2025
 */
export function createFlashProductRelation(data) {
  return request({
    url:'/flashProductRelation/create',
    method:'post',
    data:data
  })
}

/**
 * 删除限时购商品关联
 * @param {number} id - 限时购商品关联ID
 * @returns {Promise} 返回删除结果的Promise对象
 * generated by zhangsan 2025
 */
export function deleteFlashProductRelation(id) {
  return request({
    url:'/flashProductRelation/delete/'+id,
    method:'post'
  })
}

/**
 * 更新限时购商品关联
 * @param {number} id - 限时购商品关联ID
 * @param {Object} data - 更新的数据对象
 * @param {number} data.flashPromotionId - 限时购活动ID
 * @param {number} data.flashPromotionSessionId - 限时购场次ID
 * @param {number} data.productId - 商品ID
 * @param {number} data.flashPrice - 限时购价格
 * @param {number} data.flashCount - 限时购数量
 * @param {number} data.sort - 排序
 * @returns {Promise} 返回更新结果的Promise对象
 * generated by zhangsan 2025
 */
export function updateFlashProductRelation(id,data) {
  return request({
    url:'/flashProductRelation/update/'+id,
    method:'post',
    data:data
  })
}
